//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api2connect.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Dev_PortalCandidatoEntities1 : DbContext
    {
        public Dev_PortalCandidatoEntities1()
            : base("name=Dev_PortalCandidatoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<obtener_detalle_elementos_trabajo_Result> obtener_detalle_elementos_trabajo(Nullable<int> tipo)
        {
            var tipoParameter = tipo.HasValue ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtener_detalle_elementos_trabajo_Result>("obtener_detalle_elementos_trabajo", tipoParameter);
        }
    
        public virtual ObjectResult<obtener_index_elementos_trabajo_Result> obtener_index_elementos_trabajo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtener_index_elementos_trabajo_Result>("obtener_index_elementos_trabajo");
        }
    
        public virtual ObjectResult<obtener_perfiles_Result> obtener_perfiles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtener_perfiles_Result>("obtener_perfiles");
        }
    }
}
