//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administracion.
        /// </summary>
        internal static string administracion {
            get {
                return ResourceManager.GetString("administracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adminitrar Regiones.
        /// </summary>
        internal static string administrar_regiones {
            get {
                return ResourceManager.GetString("administrar_regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrar Regiones.
        /// </summary>
        internal static string admin_regiones {
            get {
                return ResourceManager.GetString("admin_regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string apellidos {
            get {
                return ResourceManager.GetString("apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Candidatos.
        /// </summary>
        internal static string candidatos {
            get {
                return ResourceManager.GetString("candidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CV.
        /// </summary>
        internal static string cv {
            get {
                return ResourceManager.GetString("cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declaración de información legal.
        /// </summary>
        internal static string declaracion {
            get {
                return ResourceManager.GetString("declaracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Regiones.
        /// </summary>
        internal static string editar_regiones {
            get {
                return ResourceManager.GetString("editar_regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string eliminar {
            get {
                return ResourceManager.GetString("eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        internal static string enviar {
            get {
                return ResourceManager.GetString("enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escribir un apellido correcto.
        /// </summary>
        internal static string errApellido {
            get {
                return ResourceManager.GetString("errApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un archivo de tipos .doc, .docx o .pdf.
        /// </summary>
        internal static string errArchivo {
            get {
                return ResourceManager.GetString("errArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El file debe ocupar menos de 5Mb.
        /// </summary>
        internal static string errArchivoTamano {
            get {
                return ResourceManager.GetString("errArchivoTamano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escribir un e-mail correcto.
        /// </summary>
        internal static string errEmail {
            get {
                return ResourceManager.GetString("errEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escribir un nombre correcto.
        /// </summary>
        internal static string errNombre {
            get {
                return ResourceManager.GetString("errNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al actualizar los datos, Vuelva a intentarlos.
        /// </summary>
        internal static string error_datos {
            get {
                return ResourceManager.GetString("error_datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escriba uno o varios email separados por comas.
        /// </summary>
        internal static string error_emails {
            get {
                return ResourceManager.GetString("error_emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe aceptar la politica de privacidad.
        /// </summary>
        internal static string errPolitica {
            get {
                return ResourceManager.GetString("errPolitica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar al menos una region.
        /// </summary>
        internal static string errRegion {
            get {
                return ResourceManager.GetString("errRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe escribir un número de telefono correcto.
        /// </summary>
        internal static string errTelefono {
            get {
                return ResourceManager.GetString("errTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Examinar.
        /// </summary>
        internal static string examinar {
            get {
                return ResourceManager.GetString("examinar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de insercion.
        /// </summary>
        internal static string fecha_insercion {
            get {
                return ResourceManager.GetString("fecha_insercion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro regiones.
        /// </summary>
        internal static string flitro_region {
            get {
                return ResourceManager.GetString("flitro_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de Candidatos.
        /// </summary>
        internal static string lista_candidatos {
            get {
                return ResourceManager.GetString("lista_candidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay candidatos.
        /// </summary>
        internal static string no_candidatos {
            get {
                return ResourceManager.GetString("no_candidatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permisos para acceder.
        /// </summary>
        internal static string no_permisos {
            get {
                return ResourceManager.GetString("no_permisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string ph_apellidos {
            get {
                return ResourceManager.GetString("ph_apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string ph_email {
            get {
                return ResourceManager.GetString("ph_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string ph_nombre {
            get {
                return ResourceManager.GetString("ph_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione una o varias regiones.
        /// </summary>
        internal static string ph_sel_region {
            get {
                return ResourceManager.GetString("ph_sel_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string ph_telefono {
            get {
                return ResourceManager.GetString("ph_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He leído la politica de privacidad * y la acepto.
        /// </summary>
        internal static string politica {
            get {
                return ResourceManager.GetString("politica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portal del candidato.
        /// </summary>
        internal static string portal_candidato {
            get {
                return ResourceManager.GetString("portal_candidato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regiones.
        /// </summary>
        internal static string regiones {
            get {
                return ResourceManager.GetString("regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sede.
        /// </summary>
        internal static string sede {
            get {
                return ResourceManager.GetString("sede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona archivo.
        /// </summary>
        internal static string sel_archivo {
            get {
                return ResourceManager.GetString("sel_archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione las regiones.
        /// </summary>
        internal static string sel_regiones {
            get {
                return ResourceManager.GetString("sel_regiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string telefono {
            get {
                return ResourceManager.GetString("telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visto.
        /// </summary>
        internal static string visto {
            get {
                return ResourceManager.GetString("visto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string volver {
            get {
                return ResourceManager.GetString("volver", resourceCulture);
            }
        }
    }
}
