//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arvato.PortalCandidatoAdmin.UI.analytics
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "analytics.analyticsSoap")]
    public interface analyticsSoap
    {

        // CODEGEN: El parámetro 'loginACD' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/newAccess", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        Arvato.PortalCandidatoAdmin.UI.analytics.newAccessResponse newAccess(Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/newAccess", ReplyAction = "*")]
        System.Threading.Tasks.Task<Arvato.PortalCandidatoAdmin.UI.analytics.newAccessResponse> newAccessAsync(Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "newAccess", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class newAccessRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string application;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public string resource;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> loginACD;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
        public string domainUser;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
        public string domain;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> personPK;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 6)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> projectPK;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 7)]
        public string project;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> subProjectPK;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 9)]
        public string subProject;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 10)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> servicePK;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 11)]
        public string service;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 12)]
        public string clientInfo;

        public newAccessRequest()
        {
        }

        public newAccessRequest(string application, string resource, System.Nullable<int> loginACD, string domainUser, string domain, System.Nullable<int> personPK, System.Nullable<int> projectPK, string project, System.Nullable<int> subProjectPK, string subProject, System.Nullable<int> servicePK, string service, string clientInfo)
        {
            this.application = application;
            this.resource = resource;
            this.loginACD = loginACD;
            this.domainUser = domainUser;
            this.domain = domain;
            this.personPK = personPK;
            this.projectPK = projectPK;
            this.project = project;
            this.subProjectPK = subProjectPK;
            this.subProject = subProject;
            this.servicePK = servicePK;
            this.service = service;
            this.clientInfo = clientInfo;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "newAccessResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class newAccessResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public bool newAccessResult;

        public newAccessResponse()
        {
        }

        public newAccessResponse(bool newAccessResult)
        {
            this.newAccessResult = newAccessResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface analyticsSoapChannel : Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class analyticsSoapClient : System.ServiceModel.ClientBase<Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap>, Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap
    {

        public analyticsSoapClient()
        {
        }

        public analyticsSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public analyticsSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public analyticsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public analyticsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Arvato.PortalCandidatoAdmin.UI.analytics.newAccessResponse Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap.newAccess(Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest request)
        {
            return base.Channel.newAccess(request);
        }

        public bool newAccess(string application, string resource, System.Nullable<int> loginACD, string domainUser, string domain, System.Nullable<int> personPK, System.Nullable<int> projectPK, string project, System.Nullable<int> subProjectPK, string subProject, System.Nullable<int> servicePK, string service, string clientInfo)
        {
            Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest inValue = new Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest();
            inValue.application = application;
            inValue.resource = resource;
            inValue.loginACD = loginACD;
            inValue.domainUser = domainUser;
            inValue.domain = domain;
            inValue.personPK = personPK;
            inValue.projectPK = projectPK;
            inValue.project = project;
            inValue.subProjectPK = subProjectPK;
            inValue.subProject = subProject;
            inValue.servicePK = servicePK;
            inValue.service = service;
            inValue.clientInfo = clientInfo;
            Arvato.PortalCandidatoAdmin.UI.analytics.newAccessResponse retVal = ((Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap)(this)).newAccess(inValue);
            return retVal.newAccessResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Arvato.PortalCandidatoAdmin.UI.analytics.newAccessResponse> Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap.newAccessAsync(Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest request)
        {
            return base.Channel.newAccessAsync(request);
        }

        public System.Threading.Tasks.Task<Arvato.PortalCandidatoAdmin.UI.analytics.newAccessResponse> newAccessAsync(string application, string resource, System.Nullable<int> loginACD, string domainUser, string domain, System.Nullable<int> personPK, System.Nullable<int> projectPK, string project, System.Nullable<int> subProjectPK, string subProject, System.Nullable<int> servicePK, string service, string clientInfo)
        {
            Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest inValue = new Arvato.PortalCandidatoAdmin.UI.analytics.newAccessRequest();
            inValue.application = application;
            inValue.resource = resource;
            inValue.loginACD = loginACD;
            inValue.domainUser = domainUser;
            inValue.domain = domain;
            inValue.personPK = personPK;
            inValue.projectPK = projectPK;
            inValue.project = project;
            inValue.subProjectPK = subProjectPK;
            inValue.subProject = subProject;
            inValue.servicePK = servicePK;
            inValue.service = service;
            inValue.clientInfo = clientInfo;
            return ((Arvato.PortalCandidatoAdmin.UI.analytics.analyticsSoap)(this)).newAccessAsync(inValue);
        }
    }
}
